sudo: required
services:
  - docker

before_install:
  - docker build -t divyansh27/react-test -f ./client/Dockerfile.dev ./client

# run the image and default command will be run test -- --coverage is to ensure that the tests exits

script:
  - docker run -e CI=true divyansh27/react-test npm test

#once all tests passes create images and push to docker hub
after_success:
  - docker build -t divyansh27/multi-client ./client
  - docker build -t divyansh27/multi-server ./server
  - docker build -t divyansh27/multi-worker ./worker
  - docker build -t divyansh27/multi-nginx ./nginx
# Login to docker hub

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push images to docker hub

  - docker push divyansh27/multi-client
  - docker push divyansh27/multi-server
  - docker push divyansh27/multi-worker
  - docker push divyansh27/multi-nginx 

